package com.example.himanshu.clouddatabase;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;

import java.util.HashMap;
import java.util.Map;

public class MainActivity extends AppCompatActivity {
    TextView firedata;
    public String userId;
    Firebase mRef;
    public static int i =0;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Firebase.setAndroidContext(this);
        firedata = (TextView)findViewById(R.id.firedata);
        mRef = new Firebase("https://blinding-heat-4834.firebaseio.com");
        Button submit = (Button)findViewById(R.id.submit);
        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                EditText myText = (EditText) findViewById(R.id.myText);
                String text = myText.getText().toString();
                Toast.makeText(MainActivity.this, text, Toast.LENGTH_LONG).show();

                Firebase sonRef = mRef.child("Users").child("Deo Narayan Thakur/son");
                User shiv = new User("Shiv Kumar", "1961");
                User him = new User("Himanshu Kumar", "1992");
                User ashu = new User("Ashutosh Kumar", "1989");
                User nitu = new User("Nitu Kumari", "1986");
                User neha = new User("Neha Kumari", "1988");
                Firebase postRef = mRef.child("Family");


                Firebase newPostRef = postRef.push();



                // Get the unique ID generated by push()
                String postId = newPostRef.getKey();

//                Firebase postRef1 = mRef.child("Family/" + shiv.getName());
                Firebase father = mRef.child("Family/"+shiv.getName());
                father.setValue(shiv);

                Firebase daughter1 = mRef.child("Family/"+shiv.getName() + "/Children/" + nitu.getName());
                daughter1.setValue(nitu);

                Firebase daughter2 = mRef.child("Family/"+shiv.getName() + "/Children/" + neha.getName());
                daughter2.setValue(neha);

                Firebase son1 = mRef.child("Family/"+shiv.getName() + "/Children/" + ashu.getName());
                son1.setValue(ashu);

                Firebase son2 = mRef.child("Family/" + shiv.getName() + "/Children/" + him.getName());
                son2.setValue(him);

//                Map<String, String> post1 = new HashMap<String, String>();
//                post1.put("Name", "Himanshu2");
//                son2.updateChildren(post1);
//                post1.put("Name", nitu.getName());
//                post1.put("BirthYear", nitu.getBirthYear());


//                post1.put("Name", neha.getName());
//                post1.put("BirthYear", neha.getBirthYear());
//
//
//
//                post1.put("Name", ashu.getName());
//                post1.put("BirthYear", ashu.getBirthYear());
//
//
//                post1.put("Name", him.getName());
//                post1.put("BirthYear", him.getBirthYear());
//                postRef1.push().setValue(post1);

                // mRef.child(String.valueOf(i)).setValue(text);


            }
        });

        mRef.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
//                String superdata = (String) dataSnapshot.getValue();
//                //Log.i("My Text", superdata);
//                //firedata.setText(superdata);
 
                Log.i("my Data", String.valueOf(dataSnapshot.getChildrenCount()));
//                for(int i=0; i<dataSnapshot.getChildrenCount();i++){
//                    Log.i("my Data", dataSnapshot.getChildren());
//                }

            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        });



    }
}
